### ISSUE TITLE
Great Project

### ISSUE THREAD

**Issue by weweco123** [rmccrystal/modernwarfare-cheat-rs#1]
I often play this game. When I saw this project, it attracted me and made me start learning Rust language. Today is the first day of study. And every time you update it in time. Thanks for your contribution.

**Comment by weweco123** [comment]
When I run the program, I ran into some problems. help please.
   Compiling memlib v0.1.0 (G:\abc\rust_project\memlib-rs)
error[E0433]: failed to resolve: could not find `unix` in `os`
 --> G:\abc\rust_project\memlib-rs\src\overlay\looking_glass.rs:6:14
  |
6 | use std::os::unix::fs::OpenOptionsExt;
  |              ^^^^ could not find `unix` in `os`

error[E0433]: failed to resolve: use of undeclared type or module `libc`
  --> G:\abc\rust_project\memlib-rs\src\overlay\looking_glass.rs:26:27
   |
26 |             .custom_flags(libc::O_NONBLOCK)
   |                           ^^^^ use of undeclared type or module `libc`

warning: unused import: `tarpc::client`
  --> G:\abc\rust_project\memlib-rs\src\system\mod.rs:10:5
   |
10 | use tarpc::client;
   |     ^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused import: `Bytes`
 --> G:\abc\rust_project\memlib-rs\src\overlay\looking_glass.rs:5:22
  |
5 | use std::io::{Write, Bytes};
  |                      ^^^^^

error[E0599]: no method named `custom_flags` found for mutable reference `&mut std::fs::OpenOptions` in the current scope
  --> G:\abc\rust_project\memlib-rs\src\overlay\looking_glass.rs:26:14
   |
26 |             .custom_flags(libc::O_NONBLOCK)
   |              ^^^^^^^^^^^^ method not found in `&mut std::fs::OpenOptions`
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
           `use std::os::windows::fs::OpenOptionsExt;`

error: aborting due to 3 previous errors; 2 warnings emitted

Some errors have detailed explanations: E0433, E0599.
For more information about an error, try `rustc --explain E0433`.
error: could not compile `memlib`.

**Comment by genhack** [comment]
I have the same error, memlib is not for windows only emulation over virtual machine from linux

**Comment by weweco123** [comment]
> 我有同样的错误，memlib不适用于Windows，只能通过Linux虚拟机进行仿真

Can you run this library on a linux system ？I don't know which system it is running on.

**Comment by weweco123** [comment]
> I have the same error, memlib is not for windows only emulation over virtual machine from linux

Can you run this library on a linux system ？I don't know which system it is running on.

**Comment by rmccrystal** [comment]
I am working on adding support for Windows in the future. For now I've released this project as a reference for other developers.
