### ISSUE TITLE
Could not find `null_overlay` in `overlay`

### ISSUE THREAD

**Issue by RatoFofo** [rmccrystal/modernwarfare-cheat-rs#4]
Hello @rmccrystal , im tryng to learn more about Rust and im compiling this project for a few days... 

Im having a problem to initialize the `hacks::hack_loop` on main.rs because when we try to start the `overlay` like is in master branch:

`let overlay = Box::new(overlay::null_overlay::NullOverlay);`

the null_overlay do not exist in overlay in memlib... i already try a lot of things but notting was succed =(... 
I also tryd to uncomment the old code where you was starting the overlay pointer in another way:

 ```
   // Init the overlay
    // let overlay = Box::new(overlay::looking_glass::LookingGlassOverlay::new(
    //     "/tmp/overlay-pipe",
    //     false,
    //     6
    // ).expect("Failed to create overlay"));
```

But i cold not succed too...

Can you help me to understand how to initialize the overlay to pass inside the `hacks::hack_loop`

Thanks, gg =D
Discod: SilentSharp#5362
I alreaded added you btw =P

**Comment by rmccrystal** [comment]
i've been working on a bunch of stuff on memlib-rs including imgui support and cross platform overlay support. as of now this project will not work on windows.
